- name : configure shipping 
  hosts: shipping
  become: yes

  tasks:
   - name: install maven
     ansible.builtin.package:
      name: maven
      state: present

   - name: add user
     ansible.builtin.user:
      name: roboshop 
      home: /app
      shell: /sbin/nologin
      comment: roboshop

  -  name: deleting the app
     ansible.builtin.file:
      path: /app
      state: absent

  -  name: Create a directory if it does not exist
     ansible.builtin.file:
      path: /app
      state: directory

  -  name: deleting the cataolog zip file
     ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  -  name: Download 
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  -  name: Unarchive a file 
     ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  

  